### ISSUE TITLE
Can you share ClassLibrarySuperCom.dll?

### ISSUE THREAD

**Issue by glenwangwenliang** [BHughes3388/TNCNotify#1]
Hi， Thanks for your sharing. 
Can you share  with us  the ClassLibrarySuperCom.dll?
I find it cannot work without the dll.

**Comment by BHughes3388** [comment]
It’s a library you’ll have to purchase. This application is useless without the accompanying iOS app and/or a way to sign up and add machines. This is a project that is currently only being used in my shop while developing. If it’s something you’re interested in we can talk more and possible look into sharing/testing.

**Comment by glenwangwenliang** [comment]
Thanks for your reply,I got it.
